<Project Sdk="MSTest.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Handinpack.App/Handinpack.App.csproj" />
    <Compile Include="../Handinpack.Tests/FileFixture.cs" Link="FileFixture.cs" />
  </ItemGroup>
</Project>
